Add item requests
Ruslan103/java-shareit pull request #3
Opened 2023-09-10 19:10 UTC by Ruslan103

2023-09-15 13:54 UTC, mikita95 requested changes
Все сделано очень хорошо. Оставил лишь небольшие замечания

2023-09-15 13:54 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (from < 0) {
Можно вынести это дублирующийся кусок получения Pageable в утилитный класс или метод, чтобы уменьшить дублирование кода

2023-09-15 13:54 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto getIemRequestById(long requestId, long userId) {
Опечатка, должно быть Item

2023-09-15 13:54 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        } else {
Здесь можно else не писать, в предыдущей секции выполняется return

2023-09-15 19:11 UTC, Ruslan103 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto getIemRequestById(long requestId, long userId) {
Перепроверил, думаю опечатки нет... В этом методе получаем Request по id, поэтому метод принимает id запроса и id пользователя. Исправил   requestId на  itemRequestId, может так корректнее. Надеюсь я правильно понял

2023-09-16 19:16 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto getIemRequestById(long requestId, long userId) {
Имелось в виду, что в названии метода опечатка

2023-09-16 19:16 UTC, mikita95 approved these changes
Все хорошо. Можно мержить пул-реквест

2023-09-17 09:51 UTC, merged